import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""
It's like Minecraft except not.
"""

# Read 'em in!
al = pd.read_csv("data/mineral/tsv/Aluminum.tsv", sep="\t")
al2 = pd.read_csv("data/mineral/tsv/Aluminum2.tsv", sep="\t")
sb = pd.read_csv("data/mineral/tsv/Antimony.tsv", sep="\t")
sb2 = pd.read_csv("data/mineral/tsv/Antimony2.tsv", sep="\t")
bar = pd.read_csv("data/mineral/tsv/Barite.tsv", sep="\t")
bau = pd.read_csv("data/mineral/tsv/Bauxite.tsv", sep="\t")
be = pd.read_csv("data/mineral/tsv/Beryllium.tsv", sep="\t")
bi = pd.read_csv("data/mineral/tsv/Bismuth.tsv", sep="\t")
b = pd.read_csv("data/mineral/tsv/Boron.tsv", sep="\t")
br = pd.read_csv("data/mineral/tsv/Bromine.tsv", sep="\t")
cd = pd.read_csv("data/mineral/tsv/Cadmium.tsv", sep="\t")
cr = pd.read_csv("data/mineral/tsv/Chromiuim.tsv", sep="\t")
cr2 = pd.read_csv("data/mineral/tsv/Chromium2.tsv", sep="\t")
co = pd.read_csv("data/mineral/tsv/Cobalt.tsv", sep="\t")
co2 = pd.read_csv("data/mineral/tsv/Cobalt2.tsv", sep="\t")
cu = pd.read_csv("data/mineral/tsv/Copper.tsv", sep="\t")
cu2 = pd.read_csv("data/mineral/tsv/Copper2.tsv", sep="\t")
cu3 = pd.read_csv("data/mineral/tsv/Copper3.tsv", sep="\t")
cu4 = pd.read_csv("data/mineral/tsv/Copper4.tsv", sep="\t")
fel = pd.read_csv("data/mineral/tsv/Feldspar.tsv", sep="\t")
fmo = pd.read_csv("data/mineral/tsv/Ferromolybdenum.tsv", sep="\t")
fni = pd.read_csv("data/mineral/tsv/Ferronickel.tsv", sep="\t")
fno = pd.read_csv("data/mineral/tsv/Ferroniobium.tsv", sep="\t")
fsi = pd.read_csv("data/mineral/tsv/Ferrosilicon.tsv", sep="\t")
fv = pd.read_csv("data/mineral/tsv/Ferrovanadium.tsv", sep="\t")
flu = pd.read_csv("data/mineral/tsv/Fluorspar.tsv", sep="\t")
ga = pd.read_csv("data/mineral/tsv/Gallium.tsv", sep="\t")
ge = pd.read_csv("data/mineral/tsv/Germanium.tsv", sep="\t")
globalmined = pd.read_csv("data/mineral/tsv/GlobalMined.tsv", sep="\t")
globalproc = pd.read_csv("data/mineral/tsv/GlobalProcessed.tsv", sep="\t")
au = pd.read_csv("data/mineral/tsv/Gold.tsv", sep="\t")
gra = pd.read_csv("data/mineral/tsv/Graphite.tsv", sep="\t")
importmined = pd.read_csv("data/mineral/tsv/ImportMined.tsv", sep="\t")
importprod = pd.read_csv("data/mineral/tsv/ImportProduction.tsv", sep="\t")
ind = pd.read_csv("data/mineral/tsv/Indium.tsv", sep="\t")
i = pd.read_csv("data/mineral/tsv/Iodine.tsv", sep="\t")
fe = pd.read_csv("data/mineral/tsv/Iron.tsv", sep="\t")
pb = pd.read_csv("data/mineral/tsv/Lead.tsv", sep="\t")
pb2 = pd.read_csv("data/mineral/tsv/Lead2.tsv", sep="\t")
pb3 = pd.read_csv("data/mineral/tsv/Lead3.tsv", sep="\t")
li = pd.read_csv("data/mineral/tsv/Lithium.tsv", sep="\t")
mgc = pd.read_csv("data/mineral/tsv/Magnesiumcompounds.tsv", sep="\t")
mgm = pd.read_csv("data/mineral/tsv/Magnesiummetal.tsv", sep="\t")
mn = pd.read_csv("data/mineral/tsv/Manganese.tsv", sep="\t")
mn2 = pd.read_csv("data/mineral/tsv/Manganese2.tsv", sep="\t")
mn3 = pd.read_csv("data/mineral/tsv/Manganese3.tsv", sep="\t")
hg = pd.read_csv("data/mineral/tsv/Mercury.tsv", sep="\t")
mica = pd.read_csv("data/mineral/tsv/Mica.tsv", sep="\t")
mo = pd.read_csv("data/mineral/tsv/Molybdenum.tsv", sep="\t")
mon = pd.read_csv("data/mineral/tsv/Monazite.tsv", sep="\t")
ni = pd.read_csv("data/mineral/tsv/Nickel.tsv", sep="\t")
ni2 = pd.read_csv("data/mineral/tsv/Nickel2.tsv", sep="\t")
ni3 = pd.read_csv("data/mineral/tsv/NickelMisc.tsv", sep="\t")
nio = pd.read_csv("data/mineral/tsv/NickelOxide.tsv", sep="\t")
nim = pd.read_csv("data/mineral/tsv/Nickelmetal.tsv", sep="\t")
nb = pd.read_csv("data/mineral/tsv/Niobium.tsv", sep="\t")
pgm = pd.read_csv("data/mineral/tsv/PGM.tsv", sep="\t")
pdm = pd.read_csv("data/mineral/tsv/Palladium.tsv", sep="\t")
po = pd.read_csv("data/mineral/tsv/Phosphate.tsv", sep="\t")
pl = pd.read_csv("data/mineral/tsv/Platinum.tsv", sep="\t")
pot = pd.read_csv("data/mineral/tsv/Potash.tsv", sep="\t")
prodmined = pd.read_csv("data/mineral/tsv/ProductionMined.tsv", sep="\t")
prodproc = pd.read_csv("data/mineral/tsv/ProductionProcessed.tsv", sep="\t")
ree = pd.read_csv("data/mineral/tsv/REE.tsv", sep="\t")
rem = pd.read_csv("data/mineral/tsv/Rhenium.tsv", sep="\t")
se = pd.read_csv("data/mineral/tsv/Selenium.tsv", sep="\t")
si = pd.read_csv("data/mineral/tsv/Silicon.tsv", sep="\t")
ag = pd.read_csv("data/mineral/tsv/Silver.tsv", sep="\t")
smeltsn = pd.read_csv("data/mineral/tsv/SmelteredTin.tsv", sep="\t")
smeltzn = pd.read_csv("data/mineral/tsv/SmelteredZinc.tsv", sep="\t")
steel = pd.read_csv("data/mineral/tsv/Steel.tsv", sep="\t")
sr = pd.read_csv("data/mineral/tsv/Strontium.tsv", sep="\t")
s = pd.read_csv("data/mineral/tsv/Sulfur.tsv", sep="\t")
ta = pd.read_csv("data/mineral/tsv/Tantalum.tsv", sep="\t")
te = pd.read_csv("data/mineral/tsv/Tellurium.tsv", sep="\t")
sn = pd.read_csv("data/mineral/tsv/Tin.tsv", sep="\t")
ti = pd.read_csv("data/mineral/tsv/Titanium.tsv", sep="\t")
w = pd.read_csv("data/mineral/tsv/Tungsten.tsv", sep="\t")
usmined = pd.read_csv("data/mineral/tsv/USMined.tsv", sep="\t")
usproc = pd.read_csv("data/mineral/tsv/USProcessed.tsv", sep="\t")
v = pd.read_csv("data/mineral/tsv/Vanadium.tsv", sep="\t")
y = pd.read_csv("data/mineral/tsv/Yttrium.tsv", sep="\t")
zn = pd.read_csv("data/mineral/tsv/Zinc.tsv", sep="\t")
zr = pd.read_csv("data/mineral/tsv/Zirconium.tsv", sep="\t")

alldf = [al, al2, sb, sb2, bar, bau, be, bi, b, br, cd, cr, 
           cr2, co, co2, cu, cu2, cu3, cu4, fel, fmo, fni, fno, fsi, 
           fv, flu, ga, ge, globalmined, globalproc, au, gra, importmined, 
           importprod, ind, i, fe, pb, pb2, pb3, li, mgc, mgm, mn, mn2, 
           mn3, hg, mica, mo, mon, ni, ni2, ni3, nio, nim, nb, pgm, pdm, 
           po, pl, pot, prodmined, prodproc, ree, rem, se, si, ag, smeltsn, 
           smeltzn, steel, sr, s, ta, te, sn, ti, w, usmined, usproc, v, y, zn, zr]

outjson = open("data/mineral/all.json", "w")
outhtml = open("data/mineral/all.html", "w")

for df in alldf:
    outjson.write(pd.DataFrame.to_json(df, orient="table", index=False))
    outjson.write("\n")
    outhtml.write(pd.DataFrame.to_html(df, index=False))
    outhtml.write("\n")
