import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""
It's like Minecraft except not.
"""

# Read 'em in!
al = pd.read_csv("data/mineral/csv/Aluminum.csv").replace("\t", "")
al2 = pd.read_csv("data/mineral/csv/Aluminum2.csv").replace("\t", "")
sb = pd.read_csv("data/mineral/csv/Antimony.csv").replace("\t", "")
sb2 = pd.read_csv("data/mineral/csv/Antimony2.csv").replace("\t", "")
bar = pd.read_csv("data/mineral/csv/Barite.csv").replace("\t", "")
bau = pd.read_csv("data/mineral/csv/Bauxite.csv").replace("\t", "")
be = pd.read_csv("data/mineral/csv/Beryllium.csv").replace("\t", "")
bi = pd.read_csv("data/mineral/csv/Bismuth.csv").replace("\t", "")
b = pd.read_csv("data/mineral/csv/Boron.csv").replace("\t", "")
br = pd.read_csv("data/mineral/csv/Bromine.csv").replace("\t", "")
cd = pd.read_csv("data/mineral/csv/Cadmium.csv").replace("\t", "")
cr = pd.read_csv("data/mineral/csv/Chromiuim.csv").replace("\t", "")
cr2 = pd.read_csv("data/mineral/csv/Chromium2.csv").replace("\t", "")
co = pd.read_csv("data/mineral/csv/Cobalt.csv").replace("\t", "")
co2 = pd.read_csv("data/mineral/csv/Cobalt2.csv").replace("\t", "")
cu = pd.read_csv("data/mineral/csv/Copper.csv").replace("\t", "")
cu2 = pd.read_csv("data/mineral/csv/Copper2.csv").replace("\t", "")
cu3 = pd.read_csv("data/mineral/csv/Copper3.csv").replace("\t", "")
cu4 = pd.read_csv("data/mineral/csv/Copper4.csv").replace("\t", "")
fel = pd.read_csv("data/mineral/csv/Feldspar.csv").replace("\t", "")
fmo = pd.read_csv("data/mineral/csv/Ferromolybdenum.csv").replace("\t", "")
fni = pd.read_csv("data/mineral/csv/Ferronickel.csv").replace("\t", "")
fno = pd.read_csv("data/mineral/csv/Ferroniobium.csv").replace("\t", "")
fsi = pd.read_csv("data/mineral/csv/Ferrosilicon.csv").replace("\t", "")
fv = pd.read_csv("data/mineral/csv/Ferrovanadium.csv").replace("\t", "")
flu = pd.read_csv("data/mineral/csv/Fluorspar.csv").replace("\t", "")
ga = pd.read_csv("data/mineral/csv/Gallium.csv").replace("\t", "")
ge = pd.read_csv("data/mineral/csv/Germanium.csv").replace("\t", "")
globalmined = pd.read_csv("data/mineral/csv/GlobalMined.csv").replace("\t", "")
globalproc = pd.read_csv("data/mineral/csv/GlobalProcessed.csv").replace("\t", "")
au = pd.read_csv("data/mineral/csv/Gold.csv").replace("\t", "")
gra = pd.read_csv("data/mineral/csv/Graphite.csv").replace("\t", "")
importmined = pd.read_csv("data/mineral/csv/ImportMined.csv").replace("\t", "")
importprod = pd.read_csv("data/mineral/csv/ImportProduction.csv").replace("\t", "")
ind = pd.read_csv("data/mineral/csv/Indium.csv").replace("\t", "")
i = pd.read_csv("data/mineral/csv/Iodine.csv").replace("\t", "")
fe = pd.read_csv("data/mineral/csv/Iron.csv").replace("\t", "")
pb = pd.read_csv("data/mineral/csv/Lead.csv").replace("\t", "")
pb2 = pd.read_csv("data/mineral/csv/Lead2.csv").replace("\t", "")
pb3 = pd.read_csv("data/mineral/csv/Lead3.csv").replace("\t", "")
li = pd.read_csv("data/mineral/csv/Lithium.csv").replace("\t", "")
mgc = pd.read_csv("data/mineral/csv/Magnesiumcompounds.csv").replace("\t", "")
mgm = pd.read_csv("data/mineral/csv/Magnesiummetal.csv").replace("\t", "")
mn = pd.read_csv("data/mineral/csv/Manganese.csv").replace("\t", "")
mn2 = pd.read_csv("data/mineral/csv/Manganese2.csv").replace("\t", "")
mn3 = pd.read_csv("data/mineral/csv/Manganese3.csv").replace("\t", "")
hg = pd.read_csv("data/mineral/csv/Mercury.csv").replace("\t", "")
mica = pd.read_csv("data/mineral/csv/Mica.csv").replace("\t", "")
mo = pd.read_csv("data/mineral/csv/Molybdenum.csv").replace("\t", "")
mon = pd.read_csv("data/mineral/csv/Monazite.csv").replace("\t", "")
ni = pd.read_csv("data/mineral/csv/Nickel.csv").replace("\t", "")
ni2 = pd.read_csv("data/mineral/csv/Nickel2.csv").replace("\t", "")
ni3 = pd.read_csv("data/mineral/csv/NickelMisc.csv").replace("\t", "")
nio = pd.read_csv("data/mineral/csv/NickelOxide.csv").replace("\t", "")
nim = pd.read_csv("data/mineral/csv/Nickelmetal.csv").replace("\t", "")
nb = pd.read_csv("data/mineral/csv/Niobium.csv").replace("\t", "")
pgm = pd.read_csv("data/mineral/csv/PGM.csv").replace("\t", "")
pdm = pd.read_csv("data/mineral/csv/Palladium.csv").replace("\t", "")
po = pd.read_csv("data/mineral/csv/Phosphate.csv").replace("\t", "")
pl = pd.read_csv("data/mineral/csv/Platinum.csv").replace("\t", "")
pot = pd.read_csv("data/mineral/csv/Potash.csv").replace("\t", "")
prodmined = pd.read_csv("data/mineral/csv/ProductionMined.csv").replace("\t", "")
prodproc = pd.read_csv("data/mineral/csv/ProductionProcessed.csv").replace("\t", "")
ree = pd.read_csv("data/mineral/csv/REE.csv").replace("\t", "")
rem = pd.read_csv("data/mineral/csv/Rhenium.csv").replace("\t", "")
se = pd.read_csv("data/mineral/csv/Selenium.csv").replace("\t", "")
si = pd.read_csv("data/mineral/csv/Silicon.csv").replace("\t", "")
ag = pd.read_csv("data/mineral/csv/Silver.csv").replace("\t", "")
smeltsn = pd.read_csv("data/mineral/csv/SmelteredTin.csv").replace("\t", "")
smeltzn = pd.read_csv("data/mineral/csv/SmelteredZinc.csv").replace("\t", "")
steel = pd.read_csv("data/mineral/csv/Steel.csv").replace("\t", "")
sr = pd.read_csv("data/mineral/csv/Strontium.csv").replace("\t", "")
s = pd.read_csv("data/mineral/csv/Sulfur.csv").replace("\t", "")
ta = pd.read_csv("data/mineral/csv/Tantalum.csv").replace("\t", "")
te = pd.read_csv("data/mineral/csv/Tellurium.csv").replace("\t", "")
sn = pd.read_csv("data/mineral/csv/Tin.csv").replace("\t", "")
ti = pd.read_csv("data/mineral/csv/Titanium.csv").replace("\t", "")
w = pd.read_csv("data/mineral/csv/Tungsten.csv").replace("\t", "")
usmined = pd.read_csv("data/mineral/csv/USMined.csv").replace("\t", "")
usproc = pd.read_csv("data/mineral/csv/USProcessed.csv").replace("\t", "")
v = pd.read_csv("data/mineral/csv/Vanadium.csv").replace("\t", "")
y = pd.read_csv("data/mineral/csv/Yttrium.csv").replace("\t", "")
zn = pd.read_csv("data/mineral/csv/Zinc.csv").replace("\t", "")
zr = pd.read_csv("data/mineral/csv/Zirconium.csv").replace("\t", "")

csvlist = [al, al2, sb, sb2, bar, bau, be, bi, b, br, cd, cr, 
           cr2, co, co2, cu, cu2, cu3, cu4, fel, fmo, fni, fno, fsi, 
           fv, flu, ga, ge, globalmined, globalproc, au, gra, importmined, 
           importprod, ind, i, fe, pb, pb2, pb3, li, mgc, mgm, mn, mn2, 
           mn3, hg, mica, mo, mon, ni, ni2, ni3, nio, nim, nb, pgm, pdm, 
           po, pl, pot, prodmined, prodproc, ree, rem, se, si, ag, smeltsn, 
           smeltzn, steel, sr, s, ta, te, sn, ti, w, usmined, usproc, v, y, zn, zr]

outjson = open("data/mineral/all.json", "w")
outhtml = open("data/mineral/all.html", "w")

for csv in csvlist:
    outjson.write(pd.DataFrame.to_json(csv, orient="table", index=False))
    outjson.write("\n")
    outhtml.write(pd.DataFrame.to_html(csv, index=False))
    outhtml.write("\n")
